baseURL = "https://blog.srcf.net/"
languageCode = "en-gb"
title = "The SRCF blog"
resourceDir = ".resources"
canonifyurls = "true"

[taxonomies]
  author = "authors"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "abap"
